### ISSUE TITLE
Trouble reading mbtiles file

### ISSUE THREAD

**Issue by rowanwins** [b-g/tilehut#3]
Hi there,

I've been trying to use [tippecanoe](https://github.com/mapbox/tippecanoe) to generate some vector tilesets. This process appears to be working because I can upload them to my Mapbox account.

However for some reason I'm having trouble getting tilehut to read them. In the console I get
````
Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8000/countries/4/7/8.vector.pbf Failed to load resource: the server responded with a status of 404 (Not Found)
````
I also get a similar error in my powershell window
````
tile rendering error Error: Tile does not exist
````

The schema of my mbtiles file appears to be correct according to the mbtiles spec although I notice it is quite different to the sample 'tiles-world-vector.mbtiles' file that you provide.

Do you have any tips or suggestions?

Thanks,
Rowan

PS Im just trying to use the http://localhost:8000/countries/map/ link which seems super handy (if I could get it to work!)

**Comment by b-g** [comment]
Hi @rowanwins,

But your local installation works with the provided [example data sets](https://github.com/b-g/tilehut/tree/master/data)?

If so, can you provide a small example data set so that we can have a look?

As tilehut is simply a wrapper around node-mbtiles and as the most current version is 0.8.0 but we are using [0.7.1](https://github.com/b-g/tilehut/blob/master/package.json#L15) we might just have to upgrade this dependency to 0.8.0 ...

Best,
Benedikt

cc @stephanbogner / @joeyklee

**Comment by rowanwins** [comment]
Gday @b-g 

Ok think I've worked out what happened partially.

The index.html file in the map directory is looking for 
```` 
"source-layer": "admin-countries"
````
which of course my layer does not have :)

Rookie mistake!

Thanks for a great repo, very straight forward to use once you stop and actually read the code!

Cheers
Rowan

**Comment by b-g** [comment]
Thanks! 😄
